version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    expose:
      - "8000"
    networks:
      - app

  nginx:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: prod
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge
