version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["uvicorn", "backend.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app/backend
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: ["sh", "-c", "npm install && npm run dev -- --port 5175 --host 0.0.0.0"]
    expose:
      - "5175"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5174:5174"
    depends_on:
      - backend
      - frontend
    networks:
      - app

networks:
  app:
    driver: bridge
